/* genInts.cpp generates N random binary int numbers
 * and writes them to two files: one binary, one text.
 *
 * @author Joel Adams, for CS 374 at Calvin University.
 *
 * Usage: ./genInts <N> <fileName>
 *
 * The program will generate two files:
 *   <fileName>.bin (binary format) and 
 *   <fileName>.txt (text format).
 */

#include <iostream>    // cout, cerr, fixed, showpoint, ...
#include <fstream>     // ofstream, ifstream, ...
#include <vector>      // vector
#include <cassert>     // assert
#include <random>      // random_device, ...
#include <cstdlib>     // exit
using namespace std;

typedef int Item;

vector<Item> generateData(unsigned numItems, Item lo, Item hi);

int main(int argc, char** argv) {
    const Item LOW = 0;
    const Item HIGH = 9;

    if (argc != 3) {
	cerr << "\nUsage: ./generate <N> <fileName>\n\n";
	exit(1);
    }

    unsigned numItems = atoi( argv[1] );
    unsigned numBytes = numItems * sizeof(Item);
    string txtFileName = string(argv[2]) + ".txt";

    ofstream fout(txtFileName.c_str());
    assert( fout.is_open() );

    vector<Item> data = generateData(numItems, LOW, HIGH);
    cout << "\nNumbers generated:\n";
    for (unsigned i = 0; i < data.size(); ++i) {
	    cout << data[i] << '\n';
	    fout << data[i] << '\n';
    }
    fout.close();

    string binFileName = string(argv[2]) + ".bin";
    fstream outFile = std::fstream(binFileName.c_str(),
		                std::ios::out | std::ios::binary);
    outFile.write((char*)(&(data[0])), numBytes);
    outFile.close();
    cout << '\n' << data.size() << " random numbers from range " 
	 << LOW << " to " << HIGH 
         << "\n written to '" 
         << binFileName << "' (binary) and '"
         << txtFileName << "' (txt).\n" << endl;
}

/* utility to generate a vector of pseudo-random numbers
 * @param: numItems, the number of desired numbers
 * @param: lo, the bottom of the range from which the numbers are selected
 * @param: hi, the top of the range from which the numbers are selected
 * PRE: numItems > 0 && lo < hi
 * @return: a vector of size numItems, containing pseudo-random numbers
 *           from the range lo..hi.
 */
vector<Item> generateData(unsigned numItems, Item lo, Item hi)
{
    vector<Item> data(numItems);
    random_device rd;  //Will be used to obtain a seed for the random number engine
    mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    uniform_int_distribution<> distr(lo, hi);
    for (unsigned i = 0; i < numItems; ++i) {
        // Use dis to transform the random unsigned int generated by gen into a
        // int in [lo..hi). Each distr(gen) call generates a new random int.
        data[i] = distr(gen);
    }
    return data;
}
